### ISSUE TITLE
Can't create C or C++ eclipse project

### ISSUE THREAD

**Issue by Rango61** [Cute-Test/Issues#1]
java.lang.NoSuchMethodError: ch.hsr.ifs.cute.ui.project.wizard.CuteWizardHandler.getNewProjectCreationPage()Lorg/eclipse/jface/wizard/IWizardPage;
	at ch.hsr.ifs.cute.ui.project.wizard.CuteWizardHandler.initPage(CuteWizardHandler.java:77)
	at ch.hsr.ifs.cute.ui.project.wizard.CuteWizardHandler.<init>(CuteWizardHandler.java:69)
	at ch.hsr.ifs.cute.ui.project.wizard.NewCuteProjectCategoryWizard.getHandler(NewCuteProjectCategoryWizard.java:46)
	at ch.hsr.ifs.cute.ui.project.wizard.NewCuteProjectCategoryWizard.createItems(NewCuteProjectCategoryWizard.java:29)
	at org.eclipse.cdt.ui.wizards.CDTMainWizardPage.updateData(CDTMainWizardPage.java:291)
	at org.eclipse.cdt.ui.wizards.CDTMainWizardPage.createControl(CDTMainWizardPage.java:89)
	at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:175)
	at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:696)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:588)
	at org.eclipse.jface.window.Window.create(Window.java:426)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1095)
	at org.eclipse.ui.internal.actions.NewWizardShortcutAction.run(NewWizardShortcutAction.java:120)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.jface.action.ActionContributionItem$$Lambda$42/1433951975.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

**Comment by pipeaesac** [comment]
Hi Rango61, thank you for reporting your issue. 

For me this looks like you might be missing CDT. Did you follow the instructions on [https://cute-test.com/installation/](https://cute-test.com/installation/) when installing the Cute Eclipse Plug-in?

**Comment by Rango61** [comment]
Thanks for the immediate reply.

Yes there is CDT. Here is the configuration:

[cute_eclipse_configuration.txt](https://github.com/Cute-Test/Issues/files/2236063/cute_eclipse_configuration.txt)

**Comment by tcorbat** [comment]
The missing method should be provided ba a base class used in this context.
It had been added to CDT 9.1. Which version of CDT do you have installed?
It looks like you have a newer version (9.2.1). However, your
managedbuilder plug-in is only version 9.0. This is presumably the plug-in
with the plug-in that should provide the required method.

**Comment by Rango61** [comment]
Thanks for the comment. Since you indicated some version inconsistency, I run Help -> Check for Updates.

That solved the problem!

Thanks, again, and have a good weekend.
